name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.7,name=iPhone 11']
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Pods
      run: |
        pod install
    - name: Build and Test
      run: |
        xcodebuild clean test -workspace EscoteiroEspacial.xcworkspace -scheme EscoteiroEspacial -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        bash <(curl -s https://codecov.io/bash)
      env: 
        destination: ${{ matrix.destination }}
    - name: Comment Coverage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
